In [7]:
from datasets import load_dataset

df = load_dataset("tatsu-lab/alpaca", split="train")

In [8]:
df = df.to_pandas()

In [9]:
import pandas as pd
df

,instruction,input,output,text
0,Give three tips for staying healthy.,,1.Eat a balanced diet and make sure to include...,Below is an instruction that describes a task....
1,What are the three primary colors?,,"The three primary colors are red, blue, and ye...",Below is an instruction that describes a task....
2,Describe the structure of an atom.,,"An atom is made up of a nucleus, which contain...",Below is an instruction that describes a task....
3,How can we reduce air pollution?,,There are a number of ways to reduce air pollu...,Below is an instruction that describes a task....
4,Describe a time when you had to make a difficu...,,I had to make a difficult decision when I was ...,Below is an instruction that describes a task....
...,...,...,...,...
51997,Generate an example of what a resume should li...,,"Jean Tremaine\n1234 Main Street, Anytown, CA 9...",Below is an instruction that describes a task....
51998,Arrange the items given below in the order to ...,"cake, me, eating",I eating cake.,"Below is an instruction that describes a task,..."
51999,Write an introductory paragraph about a famous...,Michelle Obama,Michelle Obama is an inspirational woman who r...,"Below is an instruction that describes a task,..."
52000,Generate a list of five things one should keep...,,1. Research potential opportunities and carefu...,Below is an instruction that describes a task....
52001,Analyze the given legal document and explain t...,The following is an excerpt from a contract be...,This legal document states that Company A has ...,"Below is an instruction that describes a task,..."

In [10]:
df = df[df["input"] != ""]

In [11]:
df

,instruction,input,output,text
5,Identify the odd one out.,"Twitter, Instagram, Telegram",Telegram,"Below is an instruction that describes a task,..."
6,Explain why the following fraction is equivale...,4/16,The fraction 4/16 is equivalent to 1/4 because...,"Below is an instruction that describes a task,..."
9,Evaluate this sentence for spelling and gramma...,He finnished his meal and left the resturant,He finished his meal and left the restaurant.,"Below is an instruction that describes a task,..."
14,"Classify the following into animals, plants, a...","Oak tree, copper ore, elephant",Oak tree: Plant\n Copper ore: Mineral\n Elepha...,"Below is an instruction that describes a task,..."
17,Reverse engineer this code to create a new ver...,def factorialize(num):\n factorial = 1\n for...,def factorialize(num):\n factorial = 1\n for...,"Below is an instruction that describes a task,..."
...,...,...,...,...
51994,Create a classification algorithm for a given ...,Dataset of medical images,We can use a convolutional neural network (CNN...,"Below is an instruction that describes a task,..."
51996,Complete the following sentence by inserting a...,The sun was ____ and the sky was ____.,The sun was shining and the sky was clear.,"Below is an instruction that describes a task,..."
51998,Arrange the items given below in the order to ...,"cake, me, eating",I eating cake.,"Below is an instruction that describes a task,..."
51999,Write an introductory paragraph about a famous...,Michelle Obama,Michelle Obama is an inspirational woman who r...,"Below is an instruction that describes a task,..."
52001,Analyze the given legal document and explain t...,The following is an excerpt from a contract be...,This legal document states that Company A has ...,"Below is an instruction that describes a task,..."

In [20]:
df['instruction'] = df['instruction'].str.lower()
df['input'] = df['input'].str.lower()
df['output'] = df['output'].str.lower()
df['text'] = df['text'].str.lower()

/tmp/ipykernel_10437/1339477061.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['instruction'] = df['instruction'].str.lower()
/tmp/ipykernel_10437/1339477061.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['input'] = df['input'].str.lower()
/tmp/ipykernel_10437/1339477061.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['output'] = df['output'].str.lower()
/tmp/ipykernel_10437/1339477061.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].str.lower()

In [23]:
df.to_json('/home/sam/torch/data/alpaca.jsonl', orient='records', lines=True)